name: Get core dependency branches
description:
  Find core dependency branches of plugin-interface and plugins based on plugin
  version
author: SuperTokens

branding:
  icon: heart
  color: red

inputs:
  plugin-version:
    description: Plugin version
    required: true

outputs:
  branches:
    description: Core dependency branches
    type: object
    properties:
      plugin-interface:
        description: Core dependency branch of plugin-interface
        type: string
      postgresql:
        description: Core dependency branch of postgresql plugin
        type: string
      mysql:
        description: Core dependency branch of mysql plugin
        type: string
      mongodb:
        description: Core dependency branch of mongodb plugin
        type: string

runs:
  using: node20
  main: dist/index.js
