name: Get core dependency branches
description:
  Find core dependency branches of plugin-interface and plugins based on plugin
  version
author: SuperTokens

branding:
  icon: heart
  color: red

inputs:
  running-for:
    description: core or plugin name
    required: true

outputs:
  branches:
    description: Core dependency branches

runs:
  using: node20
  main: dist/index.js
